apiVersion: apps/v1
kind: Deployment
metadata:
  name: blue-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: blue-app
  template:
    metadata:
      labels:
        app: blue-app
    spec:
      containers:
      - name: blue-app
        image: {{ .Values.image.repository}}:{{ .Values.image.tag }}
        args:
          - -listen=:8080
          - -text="I am blue"
        ports:
        - containerPort: 8080
        
